### ISSUE TITLE
BeerJS #4 в Rocks

### ISSUE THREAD

**Issue by Olegas** [beerjs/yaroslavl#4]
Дата: 21.02
Время: 19:00
Место: бар Rocks https://vk.com/gastrorocks

**Comment by nikehin** [comment]
Предлагаю бар Rocks https://vk.com/gastrorocks

**Comment by Olegas** [comment]
Наброшу напохоливарить: https://radiojs.ru/2019/02/radiojs55-nodejs-on-backend/

**Comment by nikehin** [comment]
Место изменено: Hopmalt pub, ул. Нахимсона 11

Бар Rocks закрыт 20-21 февраля.

**Comment by xmalinov** [comment]
@IgorNovozhilov
Цитирую из телеги:


Ссылочки по теме что обсуждали вчера... Для любителей поэкспериментировать:
Приложение на Pascal  для iPhone (Lazarus):
http://wiki.lazarus.freepascal.org/iPhone/iPod_development
Хранимки на Javascript в PostgreSQL
https://plv8.github.io/

Немного от себя, утилита для оценки сложности JS кода:
https://github.com/eslintcc/eslintcc

Я вот честно искал сначало готовые утилиты поддерживащие последние стандарты JS, но ничего не нашел, если кто знает пишите, интерестно посмотреть
