### ISSUE TITLE
BeerJS #5 в Hopmalt #5

### ISSUE THREAD

**Issue by xmalinov** [beerjs/yaroslavl#5]
Дата: 28.03
Время: 19:00
Место: паб [Hopmalt](https://hopmaltpub.ru/contacts/)

Норм место
Хотелось бы холиварчика! :godmode: :suspect: :hurtrealbad: :rage1: :rage2: :rage3: :rage4: :goberserk: :feelsgood: :finnadie: :fire:

**Comment by IgorNovozhilov** [comment]
а можно в ПТ?
для холиварчика: локализация приложения на шаблонных строках. За, против, идеи.
Грубенько о чем речь:
https://gist.github.com/IgorNovozhilov/865e48e3f1bdc6c3d64d6c663033ca62

**Comment by Olegas** [comment]
В ПГ может быть шумно если там будет какая-то группа. Надо удостовериться что этого не произойдет. Но в целом лично я - за

**Comment by Olegas** [comment]
Еще наброшу для холивара - css-in-js, зачем он?

**Comment by xmalinov** [comment]
как я понял, речь не про папин гараж, а про день недели
ок, можно и пятницу

**Comment by Olegas** [comment]
Ахахаха, я прочитал ПГ ) Лично я в ПТ не смогу

**Comment by xmalinov** [comment]
Вообще, лично мне четверг удобней тоже. Да и пабы обычно не шумные в этот день.
Так что, лучше не изменять традициям
